# Generated by Django 4.0.2 on 2022-02-02 22:12

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
