# Generated by Django 4.0.2 on 2022-02-02 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffics', '0002_point_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='point',
            name='longitude',
        ),
    ]
