# Generated by Django 4.0.2 on 2022-02-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffics', '0003_remove_point_latitude_remove_point_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='traffic',
            name='description',
            field=models.CharField(default='<django.db.models.fields.IntegerField>_<django.db.models.fields.related.ForeignKey>_<django.db.models.fields.CharField>', max_length=250),
        ),
    ]
