# Generated by Django 4.0.2 on 2022-02-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffics', '0005_alter_traffic_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic',
            name='description',
            field=models.CharField(default='Traffic description', max_length=250),
        ),
    ]
