# Generated by Django 3.2.10 on 2022-02-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffics', '0009_alter_traffic_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic',
            name='description',
            field=models.CharField(default='Traffic description', max_length=250, null=True),
        ),
    ]
